sheredom/utest.h

- utest.h
Print out values when the assertion/expectation failed.
> Print bad values

- utest.h
The macros were getting more verbose and causing some CTRL+C CTRL+V coding which is never good chi.
> Make ASSERT macros use EXPECT

- utest.h
Code is a little janky but seems to work.
> First attempt at proper filtering. 

- README.md
- Format to 80 columns
- Fix some minor spelling and grammar errors
> Some minor README improvements

- test/test.c
- utest.h
The testcase is rather hacky, but verifies the option completely
> add `--list-tests` option as the complement of `--filter`

- test/CMakeLists.txt
- test/test11.c
- utest.h
> Fix the c11 build on linux by using the newer timespec_get function.

- test/main.c
- test/test.c
- test/test.cpp
- test/test11.cpp
- utest.h
> Fix possibly uninit var.

- appveyor.yml
- test/CMakeLists.txt
- test/type_printers.inc
- utest.h
> Fix issue #52.

- utest.h
> Fix C6308 warning in VS2019.

- utest.h
Address: https://github.com/sheredom/utest.h/issues/76
References:
1. https://blog.kowalczyk.info/article/j/guide-to-predefined-macros-in-c-compilers-gcc-clang-msvc-etc..html
> Add support for MSYS2 and MINGW gcc

- utest.h
Should address: https://github.com/sheredom/utest.h/issues/75
> Quieten null dereference error from gcc -fanalyzer.

- utest.h
https://github.com/sheredom/utest.h/issues/84
> Address null dereference #84

- .github/workflows/cmake.yml
- README.md
- appveyor.yml
- utest.h
> Add a way to randomize the order of the tests (using an optional --random-order argument)

- utest.h
Thought I'd have a go at trying to fix https://github.com/sheredom/utest.h/pull/86
> Try to fix #86.

- README.md
- test/test.c
- test/test.cpp
- test/test11.c
- test/test11.cpp
- test/test99.c
- utest.h
> Add a UTEST_TODO macro and the concept of skipped tests.

- utest.h
> Fix string compare

- .github/workflows/cmake.yml
- test/main.c
- test/subprocess.h
- test/test.cpp
- test/type_printers.c
- utest.h
This pulls over the MinGW testing done in subprocess.h to this repo. https://github.com/sheredom/subprocess.h/pull/71
> Add MinGW testing to utest.h.

- .github/workflows/cmake.yml
Thank you to [Kruemmelspalter](https://github.com/Kruemmelspalter) for the [solution](https://github.com/egor-tensin/setup-mingw/pull/16#issuecomment-1783251384).
> Fix for mingw CI

- test/test.c
- test/test.cpp
- test/test11.c
- test/test11.cpp
- test/test14.cpp
- test/test17.cpp
- test/test99.c
- utest.h
> Fix the char overload for testing printers under C++.

- utest.h
I asked permission from @floooh [on Mastodon](https://mastodon.gamedev.place/@floooh/113062548969723725) and he said it was ok!
> Fix the integer overflow by using a trick from Sokol.
