- utest.h
This allows a user to specify --filter=<testcase name> and filter which test case can run.
> Add support for initial filtering of tests.

- utest.h
When piping the output of utest.h into a file or pipe the default
behaviour should be to omit colour formatting as these output devices
are non-interactive and colour output confounds parsing.
In a future patch I'd like to add support to make this optional a'la
git diff --color=<auto|always|never> or gcc's
`-fdiagnostics-color=<auto|always|never>`
However, this should be sufficient for now.
> Don't emit ANSI colour escape sequences when output is not a tty

- README.md
Strings that look like \<tags\> are interpreted as \<tags\> and therefore weren't displayed. Wrapping them in \`backticks\` solves that
> Add syntax highlighting to README. Fix argument display in README

- appveyor.yml
- test/CMakeLists.txt
- test/stdint_include.c
- utest.h
Check that including stdint.h works, because we don't include it on MSVC and it was failing previously.
> Check that including stdint.h works.

- test/CMakeLists.txt
On newer versions of MSVC, the compiler warns at `/Wall` if it will
generate a FENCE to mitigate against spectre
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5045?view=vs-2019
This breaks testing, and is uninteresting for our purposes.
> Disable warnings about generated spectre mitigations

- .travis.yml
- appveyor.yml
- test/CMakeLists.txt
- test/main.c
- utest.h
This commit just uses the `__pragma(comment(linker, "symbol"));` trick
to ensure that the symbol is kept even if whole program optimization
comes along and tries to remove it.
Fixes #31.
> Keep symbols during whole program optimization (WPO).

- utest.h
CentOS-7.5.1804 gcc.4.8.5
error: unknown type name '__auto_type'
pr was tested on [gcc4.8.5 centos7.5.1804] and  [gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3  Ubuntu 20.04.1 LTS]
> fix compile error on gcc4.8.5

- test/test.c
- test/test.cpp
- test/test11.cpp
- utest.h
> *_STRNEQ & *_STRNNE no longer assumes input strings are null-terminated, instead user provides the length.

- utest.h
This is helpful for separating user test cases from each other, and also
fixes a bug wherby `UTEST_COLOUR_OUTPUT` implicity sets `errno` if the
standard streams are not connected to a tty. e.g.
```shell-session
$ cat <<EOF > test.c
UTEST(errno, not_set)
{
ASSERT_EQ(errno, 0);
}
UTEST_MAIN();
EOF
$ cc test.c
$ ./a.out
[==========] Running 1 test cases.
[ RUN      ] errno.not_set
[       OK ] errno.not_set (1747ns)
[==========] 1 test cases ran.
[  PASSED  ] 1 tests.
$ ./a.out | cat
[==========] Running 1 test cases.
[ RUN      ] errno.not_set
test.c:6: Failure
Expected : 25
Actual : 0
[  FAILED  ] errno.not_set (4892ns)
[==========] 1 test cases ran.
[  PASSED  ] 0 tests.
[  FAILED  ] 1 tests, listed below:
[  FAILED  ] errno.not_set
```
> Reset errno between tests

- test/test.cpp
- utest.h
Today I've run into problem when tried to run some tests on Win 7 and these pull request address that problem (and adds `#include <Windows.h>` to test.cpp in order to verify the fix)
However, please take these changes with grain of salt - I haven't verified that these changes does not break anything on newer MSVC compilers.
Here are detailed information about compiler in my case:
```
$ cmake .
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23918.0
-- The CXX compiler identification is MSVC 19.0.23918.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done …
```
> - fixed problem with compilation on Windows 7 / VS2015

- utest.h
References:
1. https://www.dragonflybsd.org/docs/howtos/howtoporttodragonfly/#index7h3
> Add support for DragonFlyBSD

- utest.h
```
❯ uname -a
SunOS hostname 5.11 omnios-r151040-92ae97307e i86pc i386 i86pc
❯ gcc -dM -E - < /dev/null | sort | grep 'sun'
#define __sun 1
#define __sun__ 1
#define sun 1
```
> Add support for Solaris (OmniOS)

- utest.h
```
❯ gcc -dM -E - < /dev/null | grep 'HAIKU'
#define __HAIKU__ 1
```
> Add support for Haiku.

- README.md
Noticed this while reading the documentation thought I would jump in and fix it.
> Fixed Readme ASSERT_STRNE using the wrong code example

- README.md
- test/test.c
- test/test.cpp
- test/test11.c
- test/test11.cpp
- test/test99.c
- utest.h
This commit adds `ASSERT_NEAR` and `EXPECT_NEAR` to support epsilon aware floating-point checks.
Fixes #91.
> Add support for assert/expect with epsilon.

- utest.h
Fixes #96.
This prints out like:
```
[==========] Running 1 test cases.
[ RUN      ] c.UShort
/Users/neil.henning/Home/utest.h/test/test.c:198: Failure (Expected != Actual)
Expected : 1
Actual : 1
[  FAILED  ] c.UShort (727ns)
[==========] 1 test cases ran.
[  PASSED  ] 0 tests.
[  FAILED  ] 1 tests, listed below:
[  FAILED  ] c.UShort
```
Not sure if this is actually good enough, but I'm struggling to come up with a nicer way.
> Try a fix for the `ASSERT_NE` bug.

- test/subprocess.h
There is a small typo in test/subprocess.h.
Should read `conjunction` rather than `conjuction`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, conjuction -> conjunction

- utest.h
I tried compiling with the latest version of utest on Mingw-w64 gcc version 12.2.0 (Rev10, Built by MSYS2 project)
and I'm getting this error:
```C
utest.h: error: conflicting types for 'QueryPerformanceCounter'; have 'int(utest_large_integer *)'
| UTEST_C_FUNC __declspec(dllimport) int __stdcall QueryPerformanceCounter(
note: previous declaration of 'QueryPerformanceCounter' with type 'WINBOOL(LARGE_INTEGER *)' {aka 'int(LARGE_INTEGER *)'}
|   WINBASEAPI WINBOOL WINAPI QueryPerformanceCounter (LARGE_INTEGER *lpPerformanceCount);
```
Short of a better solution, restoring this if guard fixes it (that code was removed from the PR that added mingw support, aka #115).
> Fix conflicting types for QueryPerformanceCounter.

- utest.h
I had formatted these by hand vertically but it's probably best to leave it to clang format, less hassle.
> Fix print format expects argument of type int

- .github/workflows/cmake.yml
- README.md
It would seem like Ubuntu ships TCC with a patch that includes the constructor attribute extension :)
> Add TCC CI (ubuntu only).

- utest.h
When running `scan-build` (i.e. wrapping clang's static code analyser), it'd flag a few possible memory leaks.
This PR makes things a little "safer" as far as clang is concerned (as well as a bit more consistent with each other), despite how unlikely the error state is to occur.
> scan-build fixes.

- README.md
- test/test.cpp
- test/test11.cpp
- test/test14.cpp
- test/test17.cpp
- utest.h
> Add test exception with message

- utest.h
When I recently added `EXPECT_EXCEPTION_WITH_MESSAGE` and `ASSERT_EXCEPTION_WITH_MESSAGE`, I noticed that tests need to be defined twice, once for "expect" and once for "assert". This PR is a refactor for using the same macros for tests and then defining "expect" and "assert" accordingly. Reduce the `utest.h` length from 1715 lines to 1529 lines (~11% less).  
I made a commit for each test to make it easier to review.
> Refactor tests

- README.md
- utest.h
Solve problem #129
This is another alternative to add custom messages to tests. I didn't update any test files, because macros aren't tested when they fail, so I don't see the point. Neil, if you think it's necessary to do it, I can do it. I also added a very small section in the README, because it's actually a suffix that all macros have, so I didn't want to make the README much longer unnecessarily.
> Add support for custom messages in tests

- utest.h
Fixes an error that gcc gives me when `-Wformat-truncation=2` is enabled.
```
utest.h:1135:36: error: ‘%s’ directive output truncated writing 4 bytes into a region of size 1 [-Werror=format-truncation=]
1135 |     UTEST_SNPRINTF(name, name_size, "%s", name_part);
|                                      ^~~~
```
> Fix directive output truncated writing 4 bytes into a region of size 1.

- .github/workflows/cmake.yml
- .github/workflows/sanitizers.yml
This will fix notices within the GitHub Actions UI about running on old versions of NodeJS that they want to get rid of.
> ci: Update to `actions/checkout@v4` from `v2`.

- utest.h
Setting the test case information and writing into its name should only happen when both allocations succeed; otherwise, it might be necessary to free one or both of the used pointers. utest_state.tests has to be set to NULL to avoid a UAF as well.
---
In case support for `free(NULL);` is a reasonable assumption, the code can be shortened a bit by avoiding the unnecessary conditionals. Please let me know :)
One curiosity that came up while I was looking at this and #147 is: what's the intended behavior in case memory allocation fails while instantiating test cases? I didn't take a deep look, but it seemed to me like some tests would simply be omitted, without warning the user.
> Fix logic for handling test case name allocation.

- test/test11.cpp
- test/test14.cpp
- test/test17.cpp
- utest.h
just so when you pass a boolean value in C++. this type is not define so this will hit a compiling error if you pass in a boolean type to ASSERT_EQ
> feat: add boolean eval

- README.md
The semicolon results in a compiler warning when -Wextra-semi is enabled. To be able to allow to use utest.h in projects with strict compiler flags enabled, the semicolon should be removed from the documentation.
> Remove superfluous semicolon from documentation
